import '@/styles/globals.css';
import Head from 'next/head';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

export default function App({ Component, pageProps }) {
    return (
        <>
            <Head>
                <title>Travel Along</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            {/* <Header /> */}
            <Component {...pageProps} />
        </>
    ) 
}